<template>
  <div>
    <heading-level v-bind:value="{ level: 1, text: 'プライバシーポリシー' }" />
    <div class="privacy-policy-body">
      <policy-section
        class="collection"
        title="お客様から取得する情報"
        v-bind:items="items.collection"
      >
        <p>Vがいる日々（以下当サイト）は、お客様から以下の情報を取得します。</p>
      </policy-section>
      <policy-section
        class="purpose-of-use"
        title="お客様の情報を利用する目的"
        v-bind:items="items.purposeOfUse"
      >
        <p>
          当サイトは、お客様から取得した情報を、以下の目的のために利用します。
        </p>
      </policy-section>
      <policy-section
        class="third-party"
        title="第三者提供"
        v-bind:items="items.thirdParty"
      >
        <p>
          当サイトは、お客様から取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。<br />
          但し、次の場合は除きます。
        </p>
      </policy-section>
      <policy-section title="アクセス解析ツール">
        <p>
          当サイトは、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。
          Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。
          トラフィックデータは匿名で収集されており、個人を特定するものではありません。
          Cookieを無効にすれば、これらの情報の収集を拒否することができます。
          詳しくはお使いのブラウザの設定をご確認ください。
        </p>
        <p>
          Googleアナリティクスについて、詳しくは下記リンクからご確認ください。
        </p>
        <ul class="list-disc ml-8 mt-4">
          <li>
            <link-wrapper
              href="https://marketingplatform.google.com/about/analytics/terms/jp/"
            >
              Google アナリティクス利用規約
            </link-wrapper>
          </li>
          <li>
            <link-wrapper
              href="https://www.google.com/intl/ja/policies/privacy/partners/"
            >
              ユーザーが Google パートナーのサイトやアプリを使用する際の Google
              によるデータ使用
            </link-wrapper>
          </li>
        </ul>
      </policy-section>

      <div class="disclaimer">
        <policy-section title="免責">
          <p class="copyright">
            当サイトで掲載している文章・画像・動画等の著作権・肖像権は各権利所有者に帰属します。
            記事の内容や掲載画像等に問題がある場合は、ご連絡お願いします。
          </p>
          <p class="content">
            当サイトのコンテンツは、可能な限り正確な情報を掲載するよう努めていますが、誤情報が入りこんだり、古くなっていることもあります。
            必ずしもそれらの正確性や安全性等の保証をするものではありません。<br />
            当サイトに掲載された内容によって生じたあらゆる不利益または損害に対して一切の責任を負いません。
          </p>
          <p class="other-link">
            当サイトには、他サイトへのリンクが含まれている場合があります。
            これらの外部サイトは私が運営しているものではないことに注意してください。
            したがって、リンクをクリックして他サイトへ移動された場合、それらのウェブサイトのプライバシーポリシーを確認することを強くお勧めします。<br />
            当サイトは第三者のウェブサイトやサービスにおけるコンテンツ、プライバシーポリシー等について一切の責任を負いません。
          </p>
        </policy-section>
      </div>

      <policy-section title="プライバシーポリシーの変更">
        <p>
          当サイトは、必要に応じて、このプライバシーポリシーの内容を変更します。
          この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。
        </p>
      </policy-section>
      <policy-section title="お問い合わせ">
        <p>
          お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のお問合せ先からご連絡ください。
        </p>
        <dl class="ml-4 mt-4">
          <dt class="font-semibold">運営者</dt>
          <dd class="ml-10">秋々すすき</dd>
          <dt class="font-semibold mt-2">お問い合わせ</dt>
          <dd class="ml-10">
            <link-wrapper href="/contact">お問い合わせフォーム</link-wrapper>
          </dd>
        </dl>
        <p>
          この場合、当サイトが指定する方法により、ご本人からのご請求であることの確認をさせていただきます。<br />
          なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。
        </p>
      </policy-section>
      <div class="mt-12">
        <div>制定日: 2020年10月18日</div>
        <div>改定日: 2020年10月31日 - 問い合わせ先の変更</div>
      </div>

      <div class="generated text-right mt-6">
        Generated by
        <link-wrapper href="https://kiyaku.app">KIYAKU</link-wrapper>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'
import HeadingLevel from '../atoms/HeadingLevel.vue'
import LinkWrapper from '../atoms/LinkWrapper.vue'
import PolicySection from '../organisms/PolicySection.vue'

@Component({
  components: {
    HeadingLevel,
    LinkWrapper,
    PolicySection,
  },
})
export default class PrivacyPolicy extends Vue {
  /**
   * 各節の箇条書き項目を返す。
   */
  get items() {
    return {
      collection: [
        '氏名(ニックネームやペンネームも含む)',
        'メールアドレス',
        'Cookie(クッキー)を用いて生成された識別情報',
        'OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報',
      ],
      purposeOfUse: [
        '当社サービスに関する登録の受付、お客様の本人確認、認証のため',
        'お客様の当社サービスの利用履歴を管理するため',
        '当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため',
        '市場分析、マーケティングのため',
        '提携する事業者・サービスのご案内をお送りするため',
        'お客様からのお問い合わせに対応するため',
        '当社の規約や法令に違反する行為に対応するため',
        '当社サービスの変更、提供中止、終了、契約解除をご連絡するため',
        '当社規約の変更等を通知するため',
        '以上の他、当社サービスの提供、維持、保護及び改善のため',
      ],
      thirdParty: [
        '個人データの取扱いを外部に委託する場合',
        '当社や当社サービスが買収された場合',
        '事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）',
        'その他、法律によって合法的に第三者提供が許されている場合',
      ],
    }
  }
}
</script>

<style lang="scss" scoped>
p {
  @apply mt-4;
}
</style>
