name: deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'test/**'
  workflow_dispatch:
    branches:
      - master

env:
  DEPLOY_ENV: GH_PAGES

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    env:
      ARTICLE_DIR: src/outsides/asciidocs
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }} # For private repository of submodules

      - name: update to latest submodules
        run: |
          # echo "$CREDENTIAL_HELPER_PATH" >> $GITHUB_PATH
          git config --global credential.helper "$CREDENTIAL_HELPER_PATH/git-credential-github-token"
          yarn run update-articles
        env:
          CREDENTIAL_HELPER_PATH: ${{ github.workspace }}/.github/bin
          CREDENTIAL_USERNAME: ${{ github.actor }}
          CREDENTIAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      #- name: check article sources
      #  if: ${{ env.ACT }}
      #  run: ls -al $ARTICLE_DIR && exit 1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: install offline
        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        run: yarn install --offline

      - name: compile scss
        run: yarn sass-build

      - name: output licences
        run: yarn license-file

      - name: generate
        run: yarn generate
        env:
          NODE_ENV: production

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ !env.ACT }}
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
