name: deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'test/**'
  workflow_dispatch:
    branches:
      - master

env:
  DEPLOY_ENV: GH_PAGES

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ARTICLE_DIR: src/outsides/asciidocs
    services:
      kroki:
        image: yuzutech/kroki
        env:
          KROKI_MERMAID_HOST: mermaid
        ports:
          - 8000:8000
      mermaid:
        image: yuzutech/kroki-mermaid
        ports:
          - 8002:8002
    steps:
      ### Setup
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: checkout
        uses: actions/checkout@v2

      ### Git Submodule
      - name: setup git credential
        if: ${{ !env.SKIP_SUBMOD }}
        run: |
          # echo "$CREDENTIAL_HELPER_PATH" >> $GITHUB_PATH
          git config --global credential.helper "$CREDENTIAL_HELPER_PATH/git-credential-github-token"
        env:
          CREDENTIAL_HELPER_PATH: ${{ github.workspace }}/.github/bin
          CREDENTIAL_USERNAME: ${{ github.actor }}
          CREDENTIAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: update to latest submodules
        if: ${{ !env.SKIP_SUBMOD }}
        run: |
          git submodule init
          yarn run update-articles

      - name: check article sources
        if: ${{ env.ACT }}
        run: |
          echo "::debug::Check updated aritcle sources"
          ls -al $ARTICLE_DIR

      ### Cache
      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache dependencies
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: install offline
        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        run: yarn install --offline

      ### Build
      - name: pre generate
        run: yarn sass-build && yarn license-file

      - name: generate
        run: yarn generate
        env:
          NODE_ENV: production

      ### Deploy
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ !env.ACT }}
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
